### ISSUE TITLE
Adding a manual object is not working

### ISSUE THREAD

**Issue by FernandoJungblut** [fusioninventory/sysobject.ids#41]
Added the following content

11.2.3.7.11.183 Hewlett-Packard NETWORKING JL380A HPE 1920S 8G Switch
11.2.3.7.11.184 Hewlett-Packard NETWORKING JL381A HPE 1920S 24G Switch
11.2.3.7.11.185 Hewlett-Packard NETWORKING JL382A HPE 1920S 48G Switch
11.2.3.7.11.186 Hewlett-Packard NETWORKING JL383A HPE 1920S 8G PPOE + (65W) Switch
11.2.3.7.11.187 Hewlett-Packard NETWORKING JL384A HPE 1920S 24G PPoE + (185W) Switch
11.2.3.7.11.188 Hewlett-Packard NETWORKING JL385A HPE 1920S 24G PPoE + (370W) Switch
11.2.3.7.11.198 Hewlett-Packard NETWORKING JL386A HPE 1920S 48G PPoE + (370W) Switch

In the file /usr/share/fusioninventory/sysobject.ids

restarted agent however by running the command

fusioninventory-netinventory --credentials version: 2c, community: public --debug --host 192.168.XXX.X

Still Returns

partial match for sysobjectID .1.3.6.1.4.1.11.2.3.7.11.185 in database: unknown device ID

then also added to the following file
/usr/local/share/fusioninventory/sysobject.ids

But without success.

**Comment by g-bougard** [comment]
Hi @FernandoJungblut 
you must use tabulation separator between fields an in:
```
11.2.3.7.11.183	Hewlett-Packard	NETWORKING	JL380A HPE 1920S 8G Switch
11.2.3.7.11.184	Hewlett-Packard	NETWORKING	JL381A HPE 1920S 24G Switch
11.2.3.7.11.185	Hewlett-Packard	NETWORKING	JL382A HPE 1920S 48G Switch
11.2.3.7.11.186	Hewlett-Packard	NETWORKING	JL383A HPE 1920S 8G PPOE + (65W) Switch
11.2.3.7.11.187	Hewlett-Packard	NETWORKING	JL384A HPE 1920S 24G PPoE + (185W) Switch
11.2.3.7.11.188	Hewlett-Packard	NETWORKING	JL385A HPE 1920S 24G PPoE + (370W) Switch
11.2.3.7.11.198	Hewlett-Packard	NETWORKING	JL386A HPE 1920S 48G PPoE + (370W) Switch
```
After that, the right sysobject.ids file to use depends on the installation you're using. It seems you have installed agent with a package but also from source. If you're using the system agent, forget the file under `/usr/local`.

**Comment by FernandoJungblut** [comment]
HI @g-bougard 
Thanks a lot, that was it
the file that is in the local /usr/local/share/fusioninventory/sysobject.ids

**Comment by FernandoJungblut** [comment]
One question.

now the fusioninventory is not importing the switch because the device type is not "network device"

how does the fusioninventory categorize the device know me?

**Comment by guillomovitch** [comment]
Unless something changed, you can't import a device directly from the result of a network-inventory task execution, as FIG expect a asset ID in order to associate data with something already present in its database. That's the result of original design, where this kind of task was only supposed to be run as a result of a server request.

That's (briefly) documented [here](http://fusioninventory.org/documentation/tasks/networkinventory.html):
This task can only be performed on devices already part of the list of known assets, either as a result of a previous network discovery task, or manually created, with proper SNMP credentials.
