### ISSUE TITLE
Invalid device classification (UniFi as computer)

### ISSUE THREAD

**Issue by WebGregGit** [fusioninventory/sysobject.ids#52]
Hello.

APs have been discovered but unfortunately, they were assigned to the computer category, and as a result, I cannot use the inventory task, because it only works for printers and network devices. 

Is it possible to correct the classification of Unifi access points?

**Comment by g-bougard** [comment]
Hi @WebGregGit 

I think the problem here is your APs are reporting themselves as linux or bsd appliance. If this is right, this is not possible by updating this sysobjectid.ids file. You can report the output of `# snmpget -v2c -c public "your AP IP" 1.3.6.1.2.1.1.2.0` so I can confirm.

Finally if this is the case, the only way to support UniFi AP would be to update [LinuxAppliance module](https://github.com/fusioninventory/fusioninventory-agent/blob/develop/lib/FusionInventory/Agent/SNMP/MibSupport/LinuxAppliance.pm). Or you can contact the manufacturer to produce a firmware with a better SNMP standard support, at least providing a private sysobjectid.

**Comment by WebGregGit** [comment]
snmpget returned: iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.8072.3.2.10

**Comment by g-bougard** [comment]
Hi @g-bougard 
That's a confirmation so. This OID makes the agent match this line: [sysobject.ids#L6532](https://github.com/fusioninventory/sysobject.ids/blob/1668143eee1577a012245eadcff9ff056cf711d1/sysobject.ids#L6532).
You can modify your sysobject.ids to something like:
```
8072.3.2.10	UniFi	NETWORKING	UniFi AP
```
But any networking appliance detected with this OID will be identified as UniFi AP and this is wrong. The best approach now would be to ask for a LinuxAppliance update attempt providing a snmp walk. To do so, [open another issue but for the agent](https://github.com/fusioninventory/fusioninventory-agent/issues). We won't guaranty that's possible as we need to find some other OIDs which can tell us there's an UniFi AP behind.
Then I'm closing the issue as we can't do more here.
